name: flutter_application_chat
description: "A Flutter project for chat and productivity."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  fl_chart: ^0.69.0
  circular_countdown_timer: ^0.2.4
  flutter_feather_icons: ^2.0.0+1
  flutter_shapes: ^0.3.0
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  responsive_builder: ^0.7.1
  table_calendar: ^3.1.2
  tcard: ^1.3.5
  ndialog: ^4.3.1
  bloc: ^8.1.4
  dartz: ^0.10.1
  go_router: ^14.2.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  path_provider: ^2.1.3
  slide_to_act: ^2.0.2
  sleek_circular_slider: ^2.0.1
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  change_app_package_name: ^1.3.0
  shared_preferences: ^2.3.1
  package_info_plus: ^8.0.1
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  sqflite: ^2.4.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  vibration: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/memoji/
    - lib/Tasks/assets/images/icon/iOS/icon.png
    - lib/Tasks/assets/lottie/
    - lib/Tasks/assets/images/badges/
    - lib/Tasks/assets/tutorials/
    - lib/Tasks/assets/images/pomodoro/
    - lib/Tasks/assets/audio/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "lib/assets/images/icon/iOS/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "lib/assets/images/icon/Android/foreground.png"
  adaptive_icon_background: "lib/assets/images/icon/Android/background.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: lib/assets/images/icon/iOS/icon.png
  android_12:
    image: lib/assets/images/icon/Android/foreground.png
    color: "#000000"
