// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqqyc-CtyZp5PLuOgE8_xQCXTprsttTxs',
    appId: '1:939130785725:web:bbab4e6399f25ce6dcccd4',
    messagingSenderId: '939130785725',
    projectId: 'flutterfire-ui-codelab-e3559',
    authDomain: 'flutterfire-ui-codelab-e3559.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-e3559.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVTunDN1luI1i-7iG7-G9Ar2YXhaZVf0',
    appId: '1:939130785725:android:064a31249a0e99e4dcccd4',
    messagingSenderId: '939130785725',
    projectId: 'flutterfire-ui-codelab-e3559',
    storageBucket: 'flutterfire-ui-codelab-e3559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_BEaY-fJEajnjFB0RT6EH56-3tAn5kAM',
    appId: '1:939130785725:ios:ed6e6cf8897303e1dcccd4',
    messagingSenderId: '939130785725',
    projectId: 'flutterfire-ui-codelab-e3559',
    storageBucket: 'flutterfire-ui-codelab-e3559.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_BEaY-fJEajnjFB0RT6EH56-3tAn5kAM',
    appId: '1:939130785725:ios:ed6e6cf8897303e1dcccd4',
    messagingSenderId: '939130785725',
    projectId: 'flutterfire-ui-codelab-e3559',
    storageBucket: 'flutterfire-ui-codelab-e3559.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqqyc-CtyZp5PLuOgE8_xQCXTprsttTxs',
    appId: '1:939130785725:web:16504ae3edd539cedcccd4',
    messagingSenderId: '939130785725',
    projectId: 'flutterfire-ui-codelab-e3559',
    authDomain: 'flutterfire-ui-codelab-e3559.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-e3559.firebasestorage.app',
  );
}
